use QER
go

create table dbo.barra_factor_returns (
  month_end_dt	datetime	not null,
  ri1		float		null,
  ri2		float		null,
  ri3		float		null,
  ri4		float		null,
  ri5		float		null,
  ri6		float		null,
  ri7		float		null,
  ri8		float		null,
  ri9		float		null,
  ri10		float		null,
  ri11		float		null,
  ri12		float		null,
  ri13		float		null,
  ind1		float		null,
  ind2		float		null,
  ind3		float		null,
  ind4		float		null,
  ind5		float		null,
  ind6		float		null,
  ind7		float		null,
  ind8		float		null,
  ind9		float		null,
  ind10		float		null,
  ind11		float		null,
  ind12		float		null,
  ind13		float		null,
  ind14		float		null,
  ind15		float		null,
  ind16		float		null,
  ind17		float		null,
  ind18		float		null,
  ind19		float		null,
  ind20		float		null,
  ind21		float		null,
  ind22		float		null,
  ind23		float		null,
  ind24		float		null,
  ind25		float		null,
  ind26		float		null,
  ind27		float		null,
  ind28		float		null,
  ind29		float		null,
  ind30		float		null,
  ind31		float		null,
  ind32		float		null,
  ind33		float		null,
  ind34		float		null,
  ind35		float		null,
  ind36		float		null,
  ind37		float		null,
  ind38		float		null,
  ind39		float		null,
  ind40		float		null,
  ind41		float		null,
  ind42		float		null,
  ind43		float		null,
  ind44		float		null,
  ind45		float		null,
  ind46		float		null,
  ind47		float		null,
  ind48		float		null,
  ind49		float		null,
  ind50		float		null,
  ind51		float		null,
  ind52		float		null,
  ind53		float		null,
  ind54		float		null,
  ind55		float		null,
  primary key (month_end_dt)
)
go
